@startuml

actor User

box "Frontend" #LightBlue
    participant HomepageScreen as HS
    participant ModifyMaterialScreen as MMS
    participant ApiService as AS
end box

box "Backend" #LightYellow
    participant MaterialsRouter as MR
    participant MaterialsService as MS
    participant Database as DB
end box

User -> HS: Open application
activate HS
HS -> User: Check if connected
alt User is connected
    HS -> User: Display list of materials
    User -> HS: Choose material
    User -> HS: Press edit icon
    HS -> MMS: Display modify material screen
    deactivate HS
    activate MMS
    MMS -> User: Modify material information
    User -> MMS: Select 'Update'
    MMS -> AS: Submit updated information
    deactivate MMS
    activate AS
    AS -> MR: API Call to update material information
    deactivate AS
    activate MR
    MR -> MS: Forward updated information
    deactivate MR
    activate MS
    MS -> DB: Update material information
    activate DB
    DB -> MS: Confirm information updated
    deactivate DB
    MS -> MR: Confirm update success
    activate MR
    MR -> AS: Confirm update success
    deactivate MS
    deactivate MR
    activate AS
    AS -> MMS: Display update success message
    deactivate AS
    activate MMS
    MMS -> HS: Navigate back to Homepage
    deactivate MMS
    activate HS
    HS -> User: Display updated materials list
    deactivate HS
else User is not connected
    HS -> User: Display login screen
    deactivate HS
end

@enduml