@startuml

actor User

box "Frontend" #LightBlue
    participant Application as App
    participant HomepageScreen as HS
    participant ApiService as AS
end box

box "Backend" #LightYellow
    participant MaterialsRouter as MR
    participant MaterialsService as MS
    participant Database as DB
end box

User -> App: Open application
activate App
App -> User: Check if connected
alt User is connected
    App -> HS: Navigate to Homepage
    deactivate App
    activate HS
    HS -> User: Display list of materials
    User -> HS: Choose material
    User -> HS: Select 'Remove' for chosen material
    HS -> User: Confirm removal action
    User -> HS: Confirm removal
    HS -> AS: Request to remove material
    deactivate HS
    activate AS
    AS -> MR: API Call to remove material
    deactivate AS
    activate MR
    MR -> MS: Remove material
    deactivate MR
    activate MS
    MS -> DB: Delete material from DB
    activate DB
    DB -> MS: Confirm material deleted
    deactivate DB
    MS -> MR: Confirm material removed
    activate MR
    MR -> AS: Confirm material removed
    deactivate MS
    deactivate MR
    activate AS
    AS -> HS: Confirm material removed
    deactivate AS
    activate HS
    HS -> User: Update materials list
    deactivate HS
else User is not connected
    App -> User: Display login screen
    deactivate App
end

@enduml